### ISSUE TITLE
Some tests require `ed` and fail if it is not installed

### ISSUE THREAD

**Issue by cakebaker** [uutils/diffutils#39]
When running `cargo test` the following tests fail if [ed](https://www.gnu.org/software/ed/ed.html) is not installed:

* ed_diff::tests::test_permutations
* ed_diff::tests::test_permutations_empty_lines
* ed_diff::tests::test_permutations_reverse

They fail because they call `Command::new("ed")`.

**Comment by oSoMoN** [comment]
The Git for Windows installer installs a number of standard Unix executables in `C:\Program Files\Git\usr\bin\`. Unfortunately, `ed` isn't one of them.

**Comment by marc-hb** [comment]
I suspect it's practically impossible for any Unix NOT to have `ed`. So, adding "Windows" in the name of this issue would not hurt :-)

**Comment by cakebaker** [comment]
@marc-hb I think the issue is platform-independent. Personally, I noticed it on Linux.

**Comment by marc-hb** [comment]
> When running cargo test the following 3 tests fail if [ed](https://www.gnu.org/software/ed/ed.html) is not installed `ed_diff::tests::*` They fail because they call Command::new("ed").

Is this really a bug? These tests validate the output of `diff --ed ...` and `ed` is required for that.

> > I suspect it's practically impossible for any Unix NOT to have ed.

> I think the issue is platform-independent. Personally, I noticed it on Linux.

I had a closer look and and you are right, it's much easier than I expected not to have `ed` on Linux:

```
sudo dnf remove --no-autoremove ed

Removing:
 ed          
Removing dependent packages:
 patch
 rpm-build   
```
So on Fedora this removes `patch` which is the other, much more obvious test dependency and then a lot more tests fail.

`apt-get remove ed` looks even easier and more likely: https://packages.debian.org/trixie/ed

**Comment by marc-hb** [comment]
BTW #226 makes the error message a bit more user-friendly, clearly mentioning the missing test dependency:


Without #226
```
thread 'ed_diff::tests::test_permutations_reverse' (370308) panicked at src/ed_diff.rs:399:42:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

With #226
```
thread 'ed_diff::tests::test_permutations_reverse' (385950) panicked at src/utils.rs:181:18:
Failed to start 'ed' command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

(I still think this #39 is not a bug and should be closed) EDIT: except for "skipping better": https://github.com/uutils/diffutils/pull/50#issuecomment-4398712572
